# Generated by Django 3.0.3 on 2025-01-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
